### ISSUE TITLE
segmentation fault in nfacctd

### ISSUE THREAD

**Issue by xhiksi** [pmacct/pmacct#815]
I am trying for several days to use nfacctd(built from git master) for storing to sql server(tried mysql and postgresql) netflows 9 ipfix from a mikrotik router.

Only at last, I realized that a segmentation fault inside nfacctd is occurring, repeatedly:

_DEBUG: [/etc/pmacct/nfacctd4.conf] plugin name/type: 'default'/'core'.
DEBUG: [/etc/pmacct/nfacctd4.conf] plugin name/type: 'in'/'pgsql'.
DEBUG: [/etc/pmacct/nfacctd4.conf] plugin name/type: 'out'/'pgsql'.
DEBUG: [/etc/pmacct/nfacctd4.conf] daemonize:false
DEBUG: [/etc/pmacct/nfacctd4.conf] debug:true
DEBUG: [/etc/pmacct/nfacctd4.conf] pidfile:/var/run/nfacctd.pid
DEBUG: [/etc/pmacct/nfacctd4.conf] syslog:daemon
DEBUG: [/etc/pmacct/nfacctd4.conf] aggregate[in]:src_host, dst_host, proto, src_port, dst_port, post_nat_dst_host, post_nat_dst_port, post_nat_src_host, post_nat_src_port
DEBUG: [/etc/pmacct/nfacctd4.conf] aggregate_filter[in]:dst net a.b.c.d/28
DEBUG: [/etc/pmacct/nfacctd4.conf] aggregate[out]:src_host, dst_host, proto, src_port, dst_port, post_nat_dst_host, post_nat_dst_port, post_nat_src_host, post_nat_src_port
DEBUG: [/etc/pmacct/nfacctd4.conf] aggregate_filter[out]:src net 10.100.0.0/20
DEBUG: [/etc/pmacct/nfacctd4.conf] sql_user:pmacct
DEBUG: [/etc/pmacct/nfacctd4.conf] sql_passwd:arealsmartpwd
DEBUG: [/etc/pmacct/nfacctd4.conf] sql_db:pmacct
DEBUG: [/etc/pmacct/nfacctd4.conf] sql_host:localhost
DEBUG: [/etc/pmacct/nfacctd4.conf] sql_optimize_clauses:true
DEBUG: [/etc/pmacct/nfacctd4.conf] nfacctd_ip:192.168.211.2
DEBUG: [/etc/pmacct/nfacctd4.conf] nfacctd_port:2100
DEBUG: [/etc/pmacct/nfacctd4.conf] sql_refresh_time:120
DEBUG: [/etc/pmacct/nfacctd4.conf] sql_history:10m
DEBUG: [/etc/pmacct/nfacctd4.conf] sql_history_roundoff:mh
DEBUG: [/etc/pmacct/nfacctd4.conf] sql_table_version:2
DEBUG: [/etc/pmacct/nfacctd4.conf] sql_table[in]:inbound_%m%Y
DEBUG: [/etc/pmacct/nfacctd4.conf] sql_table[out]:outbound_%m%Y
DEBUG: [/etc/pmacct/nfacctd4.conf] sql_table_schema[in]:/etc/pmacct/inbound2.sql
DEBUG: [/etc/pmacct/nfacctd4.conf] sql_table_schema[out]:/etc/pmacct/outbound2.sql
DEBUG: [/etc/pmacct/nfacctd4.conf] debug:true
AddressSanitizer:DEADLYSIGNAL

216581==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000048 (pc 0x5f81b999f43f bp 0x7f303fb0abc0 sp 0x7ffe399d29b0 T0)
==216581==The signal is caused by a READ memory access.
==216581==Hint: address points to the zero page.
    #0 0x5f81b999f43f in count_nvgre_handler /home/imath/c++/3/pmacct/src/sql_handlers.c:528
    #1 0x5f81b9962d95 in PG_cache_dbop /home/imath/c++/3/pmacct/src/pgsql_plugin.c:370
    #2 0x5f81b999506d in sql_query /home/imath/c++/3/pmacct/src/sql_common.c:3623
    #3 0x5f81b995fb3e in PG_cache_purge /home/imath/c++/3/pmacct/src/pgsql_plugin.c:559
    #4 0x5f81b9998064 in sql_cache_insert /home/imath/c++/3/pmacct/src/sql_common.c:924
    #5 0x5f81b9965d16 in pgsql_plugin /home/imath/c++/3/pmacct/src/pgsql_plugin.c:287
    #6 0x5f81b987ee83 in load_plugins /home/imath/c++/3/pmacct/src/plugin_hooks.c:291
    #7 0x5f81b97376bf in main /home/imath/c++/3/pmacct/src/nfacctd.c:1189
    #8 0x7f304242a1c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
    #9 0x7f304242a28a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
    #10 0x5f81b973fa14 in _start (/usr/local/pmacct/sbin/nfacctd+0x80a14) (BuildId: 603a509b1f45b75c03d7fe5b79858b719b59bf57)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/imath/c++/3/pmacct/src/sql_handlers.c:528 in count_nvgre_handler
==216581==ABORTING
NOTICE:  relation "outbound_092024" already exists, skipping
AddressSanitizer:DEADLYSIGNAL

216596==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000048 (pc 0x5f81b999f43f bp 0x7f303fb0abc0 sp 0x7ffe399d2a30 T0)
==216596==The signal is caused by a READ memory access.
==216596==Hint: address points to the zero page.
    #0 0x5f81b999f43f in count_nvgre_handler /home/imath/c++/3/pmacct/src/sql_handlers.c:528
    #1 0x5f81b9962d95 in PG_cache_dbop /home/imath/c++/3/pmacct/src/pgsql_plugin.c:370
    #2 0x5f81b999506d in sql_query /home/imath/c++/3/pmacct/src/sql_common.c:3623
    #3 0x5f81b995fb3e in PG_cache_purge /home/imath/c++/3/pmacct/src/pgsql_plugin.c:559
    #4 0x5f81b9981dd1 in sql_cache_handle_flush_event /home/imath/c++/3/pmacct/src/sql_common.c:481
    #5 0x5f81b996534e in pgsql_plugin /home/imath/c++/3/pmacct/src/pgsql_plugin.c:177
    #6 0x5f81b987ee83 in load_plugins /home/imath/c++/3/pmacct/src/plugin_hooks.c:291
    #7 0x5f81b97376bf in main /home/imath/c++/3/pmacct/src/nfacctd.c:1189
    #8 0x7f304242a1c9  (/lib/x86_64-linux-gnu/libc.so.6+0x2a1c9) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
    #9 0x7f304242a28a in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2a28a) (BuildId: 6d64b17fbac799e68da7ebd9985ddf9b5cb375e6)
    #10 0x5f81b973fa14 in _start (/usr/local/pmacct/sbin/nfacctd+0x80a14) (BuildId: 603a509b1f45b75c03d7fe5b79858b719b59bf57)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/imath/c++/3/pmacct/src/sql_handlers.c:528 in count_nvgre_handler
==216596==ABORTING
AddressSanitizer:DEADLYSIGNAL_

in syslog I found:

_2024-09-09T16:30:36.925342+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): Processing NetFlow/IPFIX flowset [0] from [192.168.211.1:2100] seqno [31423140]
2024-09-09T16:30:36.925435+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): NfV9 agent         : 192.168.211.1:0
2024-09-09T16:30:36.925530+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): NfV9 template type : flow
2024-09-09T16:30:36.925640+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): NfV9 template ID   : 256
2024-09-09T16:30:36.925751+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): -------------------------------------------------------------
2024-09-09T16:30:36.925845+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): |    pen     |         field type         | offset |  size  |
2024-09-09T16:30:36.925947+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | last switched      [21   ] |      0 |      4 |
2024-09-09T16:30:36.926194+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | first switched     [22   ] |      4 |      4 |
2024-09-09T16:30:36.926293+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | in packets         [2    ] |      8 |      4 |
2024-09-09T16:30:36.926387+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | in bytes           [1    ] |     12 |      4 |
2024-09-09T16:30:36.926493+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | input snmp         [10   ] |     16 |      4 |
2024-09-09T16:30:36.926594+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | output snmp        [14   ] |     20 |      4 |
2024-09-09T16:30:36.926722+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | IPv4 src addr      [8    ] |     24 |      4 |
2024-09-09T16:30:36.926815+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | IPv4 dst addr      [12   ] |     28 |      4 |
2024-09-09T16:30:36.926918+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | L4 protocol        [4    ] |     32 |      1 |
2024-09-09T16:30:36.927036+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | tos                [5    ] |     33 |      1 |
2024-09-09T16:30:36.927141+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | L4 src port        [7    ] |     34 |      2 |
2024-09-09T16:30:36.927243+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | L4 dst port        [11   ] |     36 |      2 |
2024-09-09T16:30:36.927343+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | IPv4 next hop      [15   ] |     38 |      4 |
2024-09-09T16:30:36.927434+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | IPv4 dst mask      [13   ] |     42 |      1 |
2024-09-09T16:30:36.927552+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | IPv4 src mask      [9    ] |     43 |      1 |
2024-09-09T16:30:36.927685+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | tcp flags          [6    ] |     44 |      1 |
2024-09-09T16:30:36.927782+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | sampling interval  [34   ] |     45 |      4 |
2024-09-09T16:30:36.927879+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | sampling algorithm [35   ] |     49 |      1 |
2024-09-09T16:30:36.927973+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | in dst mac         [80   ] |     50 |      6 |
2024-09-09T16:30:36.928064+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | in src mac         [56   ] |     56 |      6 |
2024-09-09T16:30:36.928158+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | out dst mac        [57   ] |     62 |      6 |
2024-09-09T16:30:36.928252+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | out src mac        [81   ] |     68 |      6 |
2024-09-09T16:30:36.928346+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | 225                [225  ] |     74 |      4 |
2024-09-09T16:30:36.928439+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | 226                [226  ] |     78 |      4 |
2024-09-09T16:30:36.928534+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | 227                [227  ] |     82 |      2 |
2024-09-09T16:30:36.928638+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | 228                [228  ] |     84 |      2 |
2024-09-09T16:30:36.928738+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): -------------------------------------------------------------
2024-09-09T16:30:36.928830+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): Netflow V9/IPFIX record size : 86
2024-09-09T16:30:36.928949+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ):
2024-09-09T16:30:36.929044+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): NfV9 agent         : 192.168.211.1:0
2024-09-09T16:30:36.929148+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): NfV9 template type : flow
2024-09-09T16:30:36.929242+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): NfV9 template ID   : 257
2024-09-09T16:30:36.929335+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): -------------------------------------------------------------
2024-09-09T16:30:36.929427+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): |    pen     |         field type         | offset |  size  |
2024-09-09T16:30:36.929519+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | ip version         [60   ] |      0 |      1 |
2024-09-09T16:30:36.929613+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | IPv6 src addr      [27   ] |      1 |     16 |
2024-09-09T16:30:36.929725+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | IPv6 src mask      [29   ] |     17 |      1 |
2024-09-09T16:30:36.929820+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | input snmp         [10   ] |     18 |      4 |
2024-09-09T16:30:36.929914+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | IPv6 dst addr      [28   ] |     22 |     16 |
2024-09-09T16:30:36.930006+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | IPv6 dst mask      [30   ] |     38 |      1 |
2024-09-09T16:30:36.930100+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | output snmp        [14   ] |     39 |      4 |
2024-09-09T16:30:36.930217+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | IPv6 next hop      [62   ] |     43 |     16 |
2024-09-09T16:30:36.930331+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | L4 protocol        [4    ] |     59 |      1 |
2024-09-09T16:30:36.930425+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | tcp flags          [6    ] |     60 |      1 |
2024-09-09T16:30:36.930518+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | sampling interval  [34   ] |     61 |      4 |
2024-09-09T16:30:36.930610+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | sampling algorithm [35   ] |     65 |      1 |
2024-09-09T16:30:36.930743+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | tos                [5    ] |     66 |      1 |
2024-09-09T16:30:36.930838+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | L4 src port        [7    ] |     67 |      2 |
2024-09-09T16:30:36.930931+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | L4 dst port        [11   ] |     69 |      2 |
2024-09-09T16:30:36.931024+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | IPv6 flow label    [31   ] |     71 |      4 |
2024-09-09T16:30:36.931075+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | 64                 [64   ] |     75 |      4 |
2024-09-09T16:30:36.931102+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | last switched      [21   ] |     79 |      4 |
2024-09-09T16:30:36.931128+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | first switched     [22   ] |     83 |      4 |
2024-09-09T16:30:36.931155+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | in bytes           [1    ] |     87 |      4 |
2024-09-09T16:30:36.931182+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | in packets         [2    ] |     91 |      4 |
2024-09-09T16:30:36.931213+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | in dst mac         [80   ] |     95 |      6 |
2024-09-09T16:30:36.931240+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | in src mac         [56   ] |    101 |      6 |
2024-09-09T16:30:36.931268+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | out dst mac        [57   ] |    107 |      6 |
2024-09-09T16:30:36.931294+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): | 0          | out src mac        [81   ] |    113 |      6 |
2024-09-09T16:30:36.931321+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): -------------------------------------------------------------
2024-09-09T16:30:36.931348+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): Netflow V9/IPFIX record size : 119
2024-09-09T16:30:36.931374+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ):
2024-09-09T16:30:36.931400+00:00 prova1234 nfacctd[216562]: DEBUG ( default/core ): Received NetFlow/IPFIX packet from [192.168.211.1:2100] version [9] seqno [31423141]_

please help me making it working

**Comment by paololucente** [comment]
Hi @xhiksi ,

This is a bug and should be fixed by the latest commit i just passed. Hope this helps, keep me posted.

Paolo
